import React from "react";
import "./index.css";

export default function DasturHaqida(){
    return(
        <div className="dastur_haqida">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. reprehenderit, eius praesentium fugit maxime saepe nemo perferendis accusantium quasi ab vero dolore ipsum, hic eaque amet consequuntur atque rerum eveniet nam pariatur! Quasi possimus ipsam placeat blanditiis numquam. Inventore quos voluptatibus animi amet eveniet, debitis quae placeat eaque et quaerat assumenda asperiores aut, nisi est voluptates necessitatibus nesciunt. Quidem pariatur tempore minima. Sed nesciunt repudiandae quasi maiores dicta est et? Voluptates architecto nihil sed veritatis adipisci dignissimos, ipsum, in autem atque obcaecati mollitia corrupti! Laudantium perferendis quo maiores voluptatem at, dolor eius, provident minima repellendus debitis enim, incidunt voluptatum autem iure quidem tempore ab ea consequuntur aut corporis dolorem minus. Numquam ea totam dolore fugit nisi facilis incidunt beatae eveniet voluptatibus error nostrum eius, odio corporis voluptatum ipsam eos, corrupti consectetur neque ab? Quasi eaque et, nostrum molestiae perferendis facilis possimus aut repellat consequuntur nesciunt, magnam dolores exercitationem aliquid cumque architecto. Nesciunt illo at facere quisquam odio numquam earum tenetur veritatis autem vitae nihil odit animi sed sapiente reprehenderit veniam, sit eius cum accusantium, iusto magni asperiores reiciendis laudantium. Nulla dolorem error minus repellendus culpa dolorum doloremque, accusantium quod distinctio ipsum voluptates ipsa quae officia reiciendis, enim quasi tenetur voluptatibus asperiores fugiat velit fuga sapiente id temporibus. Quod, placeat. Sed est nulla, amet quas harum suscipit. A libero natus ut deleniti quaerat eum dolore corrupti numquam. Soluta necessitatibus perspiciatis dolorum velit possimus ipsum nihil animi, numquam at cupiditate laborum architecto natus blanditiis, veniam a iusto quis vero molestiae exercitationem. Nemo, recusandae dolor, odio voluptate possimus commodi iusto quia ex mollitia itaque neque aliquid! Voluptatem inventore doloribus a dignissimos enim aut quasi cum architecto corrupti qui ipsam eius placeat velit magnam in, aspernatur optio!
            </p>
        </div>
    )
}